find_package(PythonInterp)
find_package(Python)

macro(srEngine_set_resource_file PROJECT SRC)
    set(WANT_BINDING ON)
    message("ARGN: ${ARGN}")
    if ("${ARGN}" MATCHES NOT_BIND)
        set(WANT_BINDING OFF)
        message("-- NOT binding resources on target ${PROJECT}")
    endif()
    set_target_properties(${PROJECT} PROPERTIES INPUT ${CMAKE_CURRENT_SOURCE_DIR}/${SRC}/ BIND_RESOURCES ${WANT_BINDING} SRC ${SRC})
endmacro()